I11: Первые Unit-тесты. TestNG + Mockito
pelgray/JobCollector pull request #20
Opened 2020-10-02 15:58 UTC by pelgray

Часть от #11 
В рамках этого PR проверяются:
- Добавление в google таблицу вакансии путем отправления http ссылки на вакансию в Telegram бот.
- Добавление в google таблицу вакансии при использовании возможности "поделиться" в мобильном приложении HeadHunter.
- Не добавляется в google таблицу ссылка на отсутствующую вакансию (некорректная ссылка).

2020-10-05 12:22 UTC, vitaly0galimsky requested changes

2020-10-05 12:22 UTC, vitaly0galimsky commented on src/test/java/com/pelgray/service/GoogleSheetsServiceTest.java
> +        }
А где проверяется, что в `appendedData` не пришло больше заголовков, чем нужно?

2020-10-05 12:22 UTC, vitaly0galimsky commented on src/test/java/com/pelgray/service/GoogleSheetsServiceTest.java
> +}
Потерялась последняя пустая строка

2020-10-05 12:22 UTC, vitaly0galimsky commented on src/test/java/com/pelgray/service/GoogleSheetsServiceTest.java
> +        }
Я правильно понимаю, что это симуляция случая, когда в таблицу добавлены свои заголовки?

2020-10-05 12:22 UTC, vitaly0galimsky commented on src/test/java/com/pelgray/service/GoogleSheetsServiceTest.java
> +                "Некорректное преобразование заголовков в названия полей класса Vacancy");
А что насчет сценария, когда в таблице нет каких-то столбцов, которые есть в классе Vacancy? Может добавить сюда симуляцию этого случая?

2020-10-05 12:22 UTC, vitaly0galimsky commented on src/test/java/com/pelgray/service/HhApiServiceTest.java
> +public class HhApiServiceTest extends Assert {
тут это наследование не нужно

2020-10-06 09:20 UTC, pelgray commented on src/main/java/com/pelgray/service/HhApiService.java
> +                    new VacancyNotFoundException();
Да, VacancyNotFoundException. Согласно [официальной информации от hh.ru](https://github.com/hhru/api/blob/master/docs/vacancies.md#%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8), код ответа при ошибке может быть только 404.
Вряд ли в будущем добавится другой метод, но вариант обработки ошибок мне нравится.

2020-10-06 10:20 UTC, pelgray commented on src/test/java/com/pelgray/service/GoogleSheetsServiceTest.java
> +        }
Да

2020-10-06 10:35 UTC, pelgray commented on src/test/java/com/pelgray/service/GoogleSheetsServiceTest.java
> +                "Некорректное преобразование заголовков в названия полей класса Vacancy");
Это не имеет смысла, поскольку метод `getOrderedFields()` делает только отображение заголовков столбцов в соответствующие названия полей `Vacancy`.
Такой кейс отработает нормально, потому что список заголовков запрашивается при каждом добавлении новой вакансии. Если и проверять, то через метод `addVacancyOnNewLine()`.

2020-10-06 11:19 UTC, vitaly0galimsky approved these changes

2020-10-06 11:19 UTC, merged