I16: Форматирование boolean-значений
pelgray/JobCollector pull request #23
Opened 2020-10-21 19:28 UTC by pelgray

Closed #16 

Вторая попытка после #22

2020-10-22 09:56 UTC, vitaly0galimsky requested changes

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/domain/SheetColumn.java
> +    boolean checkBox() default false;
Мне кажется, что этот параметр лишний. Скорее всего для всех бинарных значений будет использоваться чекбокс.

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/domain/Vacancy.java
> +    public List<CellData> getFieldsDataList(List<String> orderedFields) throws ReflectiveOperationException {
По javadoc не понятно, что теперь возвращаются параметры вакансии, которые будут в таблице (т.е. помеченные аннотацией)

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/service/GoogleSheetsService.java
>          return result;
Предлагаю заменить javadoc у метода `getOrderedFields`
```
Получение списка названий полей из класса {@link Vacancy} в той последовательности, в которой они расположены в таблице.
Если в таблице есть столбцы, созданные пользователем (их нет в классе {@link Vacancy}), то вместо названия поля возвращается пустая строка
```

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/domain/Vacancy.java
> +                // Избегаем зануленных пользовательских полей и полей, не помеченных аннотацией SheetColumn
// Пропускаем столбцы, созданные пользователем

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/domain/Vacancy.java
> +                    result.add(new CellData().setUserEnteredValue(null));
Возможно прокатит `result.add(new CellData())`

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/domain/Vacancy.java
> +                CellData cell = new CellData();
Определение ячейки можно перенести в начало цикла

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/domain/SheetColumn.java
> +    String type();
String можно заменить на enum с параметром с этими значениями

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/domain/Vacancy.java
> +                    case "formulaValue":
Стоит добавить default case

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/domain/Vacancy.java
> +                        String tmp = "-";   // Если данных нет
Возможно стоит заменить на null

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/service/GoogleSheetsService.java
> +            getSheets().batchUpdate(spreadsheetId, new BatchUpdateSpreadsheetRequest().setRequests(requests)).execute();
Стоит раскидать по объектам ради читабельности

2020-10-22 09:56 UTC, vitaly0galimsky commented on src/test/java/com/pelgray/domain/VacancyTest.java
> +                .map(t -> new CellData().setUserEnteredValue(t)).collect(Collectors.toList());
1. Предлагаю раскидать элементы списка по одному в строке и всё это в отдельный список `expectedValues`
2. orderedFields для понятности можно переименовать в actualFieldNames

2025-12-21 09:49 UTC, vitaly0galimsky requested changes

2025-12-21 09:49 UTC, vitaly0galimsky commented on build.gradle
> +    compile group: 'org.telegram', name: 'telegrambots', version: '6.9.7.1'
Начиная с 7.0 telegrambots был переименован в [telegrambots-longpolling](https://mvnrepository.com/artifact/org.telegram/telegrambots-longpolling). И там уже выпущена версия [9.2.0](https://mvnrepository.com/artifact/org.telegram/telegrambots-longpolling/9.2.0). Обновишься отдельным PR?

2025-12-21 09:49 UTC, vitaly0galimsky commented on build.gradle
> +    compile group: 'com.google.api-client', name: 'google-api-client', version: '2.0.0'
Уже выпущена версия [2.8.1](https://mvnrepository.com/artifact/com.google.api-client/google-api-client/2.8.1)

2025-12-21 09:49 UTC, vitaly0galimsky commented on build.gradle
> +    compile group: 'com.google.oauth-client', name: 'google-oauth-client-jetty', version: '1.34.1'
Есть [1.39.0](https://mvnrepository.com/artifact/com.google.oauth-client/google-oauth-client-jetty/1.39.0)

2025-12-21 09:49 UTC, vitaly0galimsky commented on build.gradle
> +    compile group: 'com.google.apis', name: 'google-api-services-sheets', version: 'v4-rev20220927-2.0.0'
Версии этого проекта вообще лучше [смотреть тут](https://central.sonatype.com/artifact/com.google.apis/google-api-services-sheets/versions).
Актуальная версия [v4-rev20251110-2.0.0](https://mvnrepository.com/artifact/com.google.apis/google-api-services-sheets/v4-rev20251110-2.0.0)

2025-12-21 09:49 UTC, vitaly0galimsky commented on src/main/java/com/pelgray/service/TelegramBotService.java
> +        this.botToken = botToken;
А зачем сохранять botToken в этом классе, если он вроде как доступен из родительного класса через метод [getBotToken](https://github.com/rubenlagus/TelegramBots/blob/v6.9.7.1/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/generics/TelegramBot.java#L16C12-L16C23)?

2025-12-21 09:54 UTC, pelgray commented on build.gradle
> +    compile group: 'org.telegram', name: 'telegrambots', version: '6.9.7.1'
Да, обновлюсь отдельным PR. Как и по остальным зависимостям. Сейчас была задача подтянуть минимальное для успешной работы кода

2025-12-21 09:56 UTC, pelgray commented on src/main/java/com/pelgray/service/TelegramBotService.java
> +        this.botToken = botToken;
Ты прав, не нужно. Решила оставить на следующие PR'ы. Здесь была задача только избавиться от использования deprecated методов

2025-12-21 09:58 UTC, vitaly0galimsky approved these changes

2025-12-21 10:16 UTC, merged